"""Render TREE.md — the cascade view of the project spine.

TREE.md is regenerated by `.github/workflows/sem-ai-tree.yml` on push to main
(Day 3). For local dev, callers can invoke `render_tree(instance)` directly.

Format:
    # SEM-AI project tree
    # (auto-generated by engine/tree_renderer.py — do not hand-edit)

    ## Vision
    - [vision-001-sem-ai](sem-ai/vision/001-sem-ai.md) — SEM-AI

    ## Goals
    - [goal-01-...](sem-ai/goals/01-...) — Outcome statement (first line)
      - children indented under the goal …

    ## ADRs
    - [adr-001-...](docs/adr/001-...) — Decision (first line)
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from .config_loader import Instance
from .graph_walker import Node, iter_spine_nodes
from .validators import section_body


def _surface(node: Node, instance: Instance) -> str:
    """Pull the summary section's first line — the surface representation."""
    spec = instance.node_types.get(node.type)
    if not spec:
        return ""
    body = section_body(node.body, spec.summary_section)
    if not body:
        return ""
    # First non-empty line, trimmed.
    for line in body.split("\n"):
        if line.strip():
            return line.strip()
    return ""


def render_tree(instance: Instance) -> str:
    """Produce the TREE.md content."""
    nodes = list(iter_spine_nodes(instance))
    by_id = {n.id: n for n in nodes}
    children: dict[str, list[Node]] = defaultdict(list)
    for n in nodes:
        if n.parent:
            children[n.parent].append(n)

    lines: list[str] = []
    lines.append("# SEM-AI project tree")
    lines.append("")
    lines.append("> Auto-generated by `engine/tree_renderer.py` — do not hand-edit. "
                 "Refreshed by `.github/workflows/sem-ai-tree.yml` on push to main.")
    lines.append("")

    def emit_subtree(node: Node, depth: int) -> None:
        rel_path = (
            node.path.relative_to(instance.root) if node.path else None
        )
        link = f"[{node.id}]({rel_path})" if rel_path else f"`{node.id}`"
        surface = _surface(node, instance)
        suffix = f" — {surface}" if surface else ""
        lines.append(f"{'  ' * depth}- {link}{suffix}")
        for child in sorted(children.get(node.id, []), key=lambda n: n.id):
            emit_subtree(child, depth + 1)

    # 1) Vision tree (vision → goals → caps → features)
    visions = sorted([n for n in nodes if n.type == "vision"], key=lambda n: n.id)
    if visions:
        lines.append("## Vision")
        lines.append("")
        for v in visions:
            emit_subtree(v, 0)
        lines.append("")

    # 2) ADR list (separate axis)
    adrs = sorted([n for n in nodes if n.type == "adr"], key=lambda n: n.id)
    if adrs:
        lines.append("## ADRs")
        lines.append("")
        for a in adrs:
            rel = a.path.relative_to(instance.root) if a.path else None
            link = f"[{a.id}]({rel})" if rel else f"`{a.id}`"
            surface = _surface(a, instance)
            chain = ""
            if a.supersedes:
                chain += f" · supersedes: {', '.join(a.supersedes)}"
            if a.superseded_by:
                chain += f" · superseded-by: {', '.join(a.superseded_by)}"
            lines.append(f"- {link} — {surface}{chain}")
        lines.append("")

    # 3) Orphans (no parent and not a root) — useful diagnostic.
    orphans = [
        n for n in nodes
        if n.type != "vision" and n.type != "adr" and (
            not n.parent or n.parent not in by_id
        )
    ]
    if orphans:
        lines.append("## Orphans (parent missing or unresolved)")
        lines.append("")
        for o in sorted(orphans, key=lambda n: n.id):
            rel = o.path.relative_to(instance.root) if o.path else None
            link = f"[{o.id}]({rel})" if rel else f"`{o.id}`"
            lines.append(f"- {link} — parent: `{o.parent or '(none)'}`")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_tree(instance: Instance, out_path: Path | None = None) -> Path:
    """Render TREE.md and write to `out_path` (defaults to <root>/TREE.md)."""
    out = out_path or (instance.root / "TREE.md")
    out.write_text(render_tree(instance), encoding="utf-8")
    return out
